spring:
  application:
    name: aipi-v1-bw20-api
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/iot}
    username: ${SPRING_R2DBC_USERNAME:api_service}
    password: ${SPRING_R2DBC_PASSWORD:api_service_password}

server:
  port: 9000
  compression:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    cn.zenghome.api: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN