
### 场景一：升级 VB6824 固件，版本号和云端不一致，开启升级

POST https://api.zenghome.cn/upgrade-cdn HTTP/1.1
Content-Type: application/json

{
  "firmwareName": "111",
  "deviceName": "112233aabbcc",
  "product": "vb6824"
}

> {%
    /// 示例响应
    /// {
    //     "success": true,
    //     "data": {
    //         "name": "你好小安 axk AiToy ChatRobot cn 1.9",
    //         "host": "aithinker-static.oss-cn-shenzhen.aliyuncs.com",
    //         "port": 443,
    //         "path": "/ota/axk_vb6824_v1.9_ota.bin",
    //         "tlsEnabled": true
    //     }
    // }
    import verifySuccessResult from './test'
    client.test('场景一：升级 VB6824 固件，版本号和云端不一致，开启升级', verifySuccessResult);
%}

### 场景二：升级 VB6824 固件，版本号和云端一致，跳过升级

POST https://api.zenghome.cn/upgrade-cdn HTTP/1.1
Content-Type: application/json

{
  "firmwareName": "你好小安 axk AiToy ChatRobot cn 1.9",
  "deviceName": "112233aabbcc",
  "product": "vb6824"
}

> {%
    /// 示例响应
    /// {
    //     "success": true,
    // }
    client.test('场景二：升级 VB6824 固件，版本号和云端一致，跳过升级', function () {
        client.assert(response.status === 200, '状态码不是 200');
        let r = response.body;
        client.assert(r.success === true, 'success 不为 true');
        client.assert(!r.hasOwnProperty('data') || r.data === null, 'data 需为空')
    });
%}

### 场景三：VB6824 没有成功上报版本号，自动拉取最新固件进行升级

POST https://api.zenghome.cn/upgrade-cdn HTTP/1.1
Content-Type: application/json

{
  "firmwareName": null,
  "deviceName": "112233aabbcc",
  "product": "vb6824"
}

> {%
    /// 示例响应
    /// {
    //     "success": true,
    //     "data": {
    //     "name": "你好小安 axk AiToy ChatRobot cn 1.9",
    //         "host": "aithinker-static.oss-cn-shenzhen.aliyuncs.com",
    //         "port": 443,
    //         "path": "/ota/axk_vb6824_v1.9_ota.bin",
    //         "tlsEnabled": true
    //     }
    // }
    import verifySuccessResult from './test'
    client.test('场景三：VB6824 没有成功上报版本号，自动拉取最新固件进行升级', verifySuccessResult);
%}

### 场景四：同场景三，省略 firmwareName 字段

POST https://api.zenghome.cn/upgrade-cdn HTTP/1.1
Content-Type: application/json

{
  "deviceName": "112233aabbcc",
  "product": "vb6824"
}

> {%
    /// 示例响应
    /// {
    //     "success": true,
    //     "data": {
    //     "name": "你好小安 axk AiToy ChatRobot cn 1.9",
    //         "host": "aithinker-static.oss-cn-shenzhen.aliyuncs.com",
    //         "port": 443,
    //         "path": "/ota/axk_vb6824_v1.9_ota.bin",
    //         "tlsEnabled": true
    //     }
    // }
    import verifySuccessResult from './test'
    client.test('场景四：同场景三，省略 firmwareName 字段', verifySuccessResult);
%}
